name: Publish

on: 
  push:
    tags: 
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
    - name: npm install, build, and test
      run: |
        echo $RELEASE_VERSION
        npm ci
        npm run build --if-present
        npm test
        npm version $RELEASE_VERSION
        npm publish --access=public
      env:
        CI: true
