name: Publish

on: 
  push:
    tags: 
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://npm.pkg.github.com/
        scope: '@beem812'
    - name: Set env
      run: |
        echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})

    - name: npm install, build, and test
      run: |
        git config --local user.name "beem812"
        npm ci
        npm run build --if-present
        npm test
        npm version $RELEASE_VERSION
        npm publish 
      env:
        NODE_AUTH_TOKEN: ${{secrets.PUBLISH_PACKAGE}}
        CI: true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'master' 
